
#Mac
# INCLUDEPATHS += /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/
# INCLUDEPATHS += /usr/local/Cellar/sdl2/2.0.8/include/
# INCLUDEPATHS += /usr/local/Cellar/freeimage/3.18.0/include/
# INCLUDEPATHS += /usr/local/Cellar/boost/1.68.0/include/

# LIBRARYPATHS += /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/
# LIBRARYPATHS += /usr/local/Cellar/sdl2/2.0.8/lib/
# LIBRARYPATHS += /usr/local/Cellar/freeimage/3.18.0/lib/
# LIBRARYPATHS += /usr/local/Cellar/boost/1.68.0/lib/

#Windows MSVC 32

# INCLUDEPATH  += C:\FreeImage\Dist\x32
# LIBRARYPATHS += C:\FreeImage\Dist\x32

# INCLUDEPATH  += C:\SDL2\SDL2-2.0.10\i686-w64-mingw32\include
# LIBRARYPATHS += C:\SDL2\SDL2-2.0.10\i686-w64-mingw32\lib

#Windows MSVC 64

# INCLUDEPATH  += C:\FreeImage\Dist\x64
# LIBRARYPATHS += C:\FreeImage\Dist\x64

# INCLUDEPATH  += C:\SDL2\msvc\SDL2-2.0.10\include
# LIBRARYPATHS += C:\SDL2\msvc\SDL2-2.0.10\lib\x64
